### PR TITLE
Add api credentials

### PR DESCRIPTION
**Pull request by hnucamendi**
#18 
In this PR I am adding the ability to use Twilio API Credentials as a method of authentication to the JWT validate endpoint. allows users to have the option to provide API token credentials and rather than root account credentials, in turn lowering the chances of those root credentials being exposed and lowering the blast radius in a worst case scenario.

I made the authToken an optional parameter, but added a check for either auth token or api credentials.

Note: I edited the `should fail to validate if response is not json` test, it seems the error message from JSON.parse() has changed, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/JSON_bad_parse

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Review by ktalebian — COMMENTED** [review]
Looks good, but why has the package-lock.json been modified?

Prefer we do a bump of package.json and fix vulns in a separate PR

**Comment by hsingla005** [comment]
Hi @hnucamendi 
The PR looks good but can you please remove the package.lock changes that you have pushed? 
We plan to close source this repo soon and also release a new version of the package (which will include changes from your PR).
Once we release the new version out, we can comment and close this PR.

**Comment by hnucamendi** [comment]
@hsingla005 @ktalebian thanks both for the comments and sorry for the delay on this - I have reverted the package-lock.json

**Comment by hnucamendi** [comment]
Hey @hsingla005 @ktalebian Just wanted to bump up this PR, having this feature implemented is something the Org at RedVentures would really appreciate!

Thanks

**Comment by hsingla005** [comment]
Hi @hnucamendi
We have close sourced this repository and have merged this PR changes in the latest released version i.e. **1.6.0**

**Comment by hnucamendi** [comment]
> Hi @hnucamendi We have close sourced this repository and have merged this PR changes in the latest released version i.e. **1.6.0**

Thanks @hsingla005  should I close this PR?

**Pull request closed without merging**
