### PR TITLE
Adding API Key Support (Closes #18)

### LINKED ISSUE #18: [FEATURE REQUEST] Ability to use an API Key instead of auth token
### Feature Request

The endpoint https://iam.twilio.com/v1/Accounts/{accountSid}/Tokens/validate accepts two authentication methods: the account SID along with the auth token, and an API key with its secret. This tool accepts only one method, though.

### Description of Solution

Implement the ability to use API keys and secrets.

### Additional Context

I'm developing an API that doesn't have access to the auth token.

### PR DESCRIPTION
**Pull request by kolencherry**
Adds in API key support to flex-token-validator.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by MartinAmps** [comment]
Huh TIL. I didn't think that endpoint _supported_ api keys yet - neat

**Comment by kolencherry** [comment]
Retracting PR

**Comment by MartinAmps** [comment]
😂pleasure, as always PK 😘

**Comment by kolencherry** [comment]
Nvm, it actually works. I'm going to reopen and write a code sample that can be used as an integration test for it. I'll also add support for functions.

**Pull request closed without merging**
